### PR TITLE
ARM64 Improvements

### PR DESCRIPTION
**Pull request by Avidanborisov**
This PR is a series of improvements for sca-fuzzer for the ARM64 architecture. 

New ARM64 Spec Generator
--------------------------------

The most notable contribution is the addition of a new `get_spec_v2.py` for ARM64, which uses information which is stored and actively maintained by the official [binutils](https://github.com/bminor/binutils-gdb/blob/5391e967b0386235b36656c77e1a3f898ab4f39d/opcodes/aarch64-tbl.h#L2844) project to create a comprehensive ISA JSON spec for ARM64. This information is retrieved from the binutils binaries themselves, by leveraging their debug symbols (using a GDB python script to parse this information). This approach leverages the already maintained and "computer-friendly" database (compared to the official English ARM64 ISA document parsed by `get_spec.py`) provided by binutils to generate an ISA. It should also make adding support for new kinds of ARM64 instructions and operands fairly easy.

Additionally, the new `get_spec_v2.py` script will only generate instructions which match the features of the currently running processor (for instance, CRC/AES/PAC etc). It retrives this information by relying on the functionality provided by `gcc -march=native` to detect the supported features, and pass them to the assembler. The list of required features to support each instruction is already embedded in the `aarch_opcode_table` database from binutils mentioned above (as a bitmap), and is compatible with `-march=native` information.

For information about implicit operands used by each instruction (which is absent from the binutils database), we use information provided by a [file from the capstone-project](https://raw.githubusercontent.com/capstone-engine/capstone/46154e8605aaefdcca5fecf4ea88b92db5a40ad3/arch/AArch64/AArch64MappingInsn.inc) (generated automatically by LLVM).

Finally the output of `get_spec_v2.py` is compatible with `get_spec.py`, and the user may choose to use either. Additionally, for convenience, pre-generated ISA JSONs of both scripts are added to the repo, as an alternative to running either generator manually.

ARM64 Spectre V1/V2/V4 POCs
-----------------------------------

Similarly to the present X86 examples, we provide pre-generated ARM64 test-cases demonstrating:

- Spectre V1 (Bounds Check Bypass)
- Spectre V2 (Branch Target Injection)
- Spectre V4 (Speculative Store Bypass)

These pre-generated test-cases were tested both on ARM64 Raspberry Pi 4 **Cortex A72**, which is known to be affected by Spectre V1/V2/V4, and ARM64 Raspberry Pi 3V1.2 **Cortex A53**, which is known to not be affected by any of the mentioned Spectre vulnerabilities. In addition, each test case has a duplicate with a slight variation which changes/comments-out instructions, so that the speculation problem should not appear. 

The results of the pre-generated test-cases are summarized in the table below (✅ - violation detected, ❌ - no violation detected).

| Test Case                            | Cortex A72 | Cortex A53 |
|------------------------------------------|------------|------------|
| Spectre V1 - BCB                         |       ✅     |      ❌      |
| Spectre V1 - BCB [no LDR under speculation] |     ❌       |     ❌       |
| Spectre V2 - BTI                         |      ✅      |       ❌     |
| Spectre V2 - BTI [no LDR under speculation] |     ❌       |     ❌       |
| Spectre V4 - SSBP                        |       ✅     |     ❌       |
| Spectre V4 - SSBP [dependent register store/load] |       ❌     |     ❌       |

which match the expected results.

ARM64 Fuzzing Improvements
----------------------------------

A new config file (`test-spectre.yaml`) is given as reference for quickly finding a V1-style violation by fuzzing (this config file is also compatible with the pre-generated test cases mentioned above). It is also good starting point for other fuzzing ideas which is compatible with the new JSON specification (the new JSON does categorize instructions, other than simply putting them under `general`).

ARM64 Tests Improvements and Bug Fixes
-----------------------------------------------

The PR fixes several bugs that failed the existing ARM64 tests (`runtests.sh arm64`), so now all ARM64 tests should pass. There are some general improvements as well (for instance, the removal of the restriction of the fuzzing to only 4 supported instructions). 

Finally, all the pre-generated test-cases mentioned above are added to the ARM64 acceptance tests, as well as a test that fuzzing finds a violation under `test-spectre.yaml`.

### CODE REVIEW

**Comment by Avidanborisov** [comment]
@microsoft-github-policy-service agree

**Comment by OleksiiOleksenko** [comment]
Thanks for the PR! And especially for such a detailed description, it's very much appreciated.

I'll need a bit of time to review the code. I'll get back to you once I'm done.

**Review by OleksiiOleksenko — APPROVED** [review]
All good and clean, no changes required

**Comment by OleksiiOleksenko** [comment]
All looks good, it's ready to merge. I really like the idea of using binutils + LLVM to get the instruction specs. Thanks!

**Pull request merged**
