### PR TITLE
Vspec fixes

### PR DESCRIPTION
**Pull request by van-ema**
The PR contains multiple fixes.
In `x86/x86_model.py`
1. In `X86UnicornVspecOps` reset `curr_mem_store` for each input
2. When we load from memory, check if the address the instruction load from overlaps with any tainted address in the range `[address, address+size] `
3. In `X86UnicornVspecAllMemoryFaults`,  Do not call `X86UnicornVspecAll.speculate_instruction` twice on the faulty instruction.

In `x86/x86_generator.py`:
When we create instrumentation, do not re-use the same operand instance. Rather, copy the operand and set the `dest` property properly.

### CODE REVIEW

**Comment by OleksiiOleksenko** [comment]
would you mind editing the history (`git rebase --interactive`) to make each fix as a separate commit?

**Comment by van-ema** [comment]
@OleksiiOleksenko Is it better now ? Let me know if I should split the commits further

**Comment by OleksiiOleksenko** [comment]
Yep, much better. Could you also prefix the commit messages with the module you're changing (see the [commit history](https://github.com/microsoft/sca-fuzzer/commits/1.2-rc1) for examples)? It simplifies rebasing this commits in the future.

**Comment by OleksiiOleksenko** [comment]
@van-ema there are a lot of conflicts after changing the target branch. Don't worry about it - I'll take care of them

**Comment by OleksiiOleksenko** [comment]
See #67

**Pull request closed without merging**
